name: dispatch

on:
  repository_dispatch:
    types: [update]
jobs:
  dispatch:
    uses: ./.github/workflows/build.yml
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
