name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY_NAME: codex
  CI: true
  IMAGE_NAME: proskurekov/base-image

jobs:
  main:
    uses: ./.github/workflows/build.yml
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}