name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY_NAME: codex
  CI: true
  IMAGE_NAME: proskurekov/base-image

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
